[package]
name = "den"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = ["bracketed-paste"] }
unicode-segmentation = "1.12.0"
unicode-width = "0.2.2"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.19"
arboard = "3.6.1"
