# JavaScript Language Configuration Example
#
# Copy this file to ~/.config/den/languages/javascript.toml

extensions = ["js", "jsx"]

keywords = [
    "function", "const", "let", "var", "if", "else", "for", "while", "do",
    "break", "continue", "return", "switch", "case", "default", "try", "catch",
    "finally", "throw", "new", "delete", "typeof", "instanceof", "in", "of",
    "class", "extends", "super", "this", "static", "async", "await",
    "import", "export", "from", "as", "yield", "debugger",
    "true", "false", "null", "undefined",
]

primitive_types = [
    "number", "string", "boolean", "symbol", "object",
    "Array", "Object", "Function", "String", "Number", "Boolean",
    "Date", "RegExp", "Map", "Set", "Promise", "Error",
]

line_comment_start = "//"
block_comment_start = "/*"
block_comment_end = "*/"

[[brackets]]
open = "("
close = ")"
color_offset = 0

[[brackets]]
open = "{"
close = "}"
color_offset = 1

[[brackets]]
open = "["
close = "]"
color_offset = 2

