# Default Color Scheme

[colors]
keyword = { r = 86, g = 156, b = 214 }
number = { r = 181, g = 206, b = 168 }
type_name = { r = 78, g = 201, b = 176 }
primitive_type = { r = 78, g = 201, b = 176 }
string = { r = 206, g = 145, b = 120 }
comment = { r = 106, g = 153, b = 85 }

[[colors.brackets]]
r = 140
g = 140
b = 140

[[colors.brackets]]
r = 97
g = 175
b = 239

[[colors.brackets]]
r = 198
g = 120
b = 221

[[colors.brackets]]
r = 152
g = 195
b = 121

